# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rose Bullet
tagline:          'The personal blog of Qian Xin'
url:              http://xeniaqian94.github.io
paginate:         1
baseurl:          /
author:
  name:           'Qian Xin'
  url:            https://twitter.com/mdo
  email:          xeniaqian94@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# pages_list:       {'About Me':'/about','Blog Posts':'/archive','Feed':'/atom.xml'}
pages_list:       {'About Me':'/about','Blog Posts':'/archive'}
